baseurl: https://bluevisual.tv/

languageCode: en-us

title: Blue Visual Website v04

publishdir: docs

module:
  mounts:
  - files:
    - '! docs/*'
    source: content
    target: content
    excludeFiles:
      - "work/_archive/*"
      - "personal/_archive/*"
  - source: static
    target: static
    excludeFiles:
      - "project-media/_archive/*"
  - source: assets
    target: assets
  - source: layouts
    target: layouts

pygmentsuseclasses: true
